### ISSUE TITLE
ERROR! Pop up with MIDI programs using OmniMIDI

### ISSUE THREAD

**Issue by dandamusix95** [KaleidonKep99/OmniMIDI#179] opened 2021-02-18 03:00 UTC
This is happening possibly due to the latest Windows 10 Update. Anytime I open a MIDI program using OmniMIDI version 13 and newer, a popup comes up saying: ERROR! This file has been tampered with and MAY BE INFECTED BY A VIRUS!

This happens with any MIDI program I've previously used before OmniMIDI v13. The only exception is SoundFont MIDI player x64 (v5.6). The pop-up in the image below appears after opening Zenith.

![Screenshot (39)](https://user-images.githubusercontent.com/53980675/108297951-15bb4a80-716a-11eb-83b6-f7e725bbe918.png)

I'm currently using OmniMIDI 13.4.0.0.

**Comment by KaleidonKep99** [comment] 2021-02-18 13:55
You're not the first one to report this, which is worrying... (#177)
I'll look into both the DLLs and the Inno Setup Compiler, to see if maybe something is getting messed up.

Do you have any antivirus by any chance? If so, could you give me their name and version?

**Comment by KaleidonKep99** [comment] 2021-02-18 14:26
Could you please enable the debug log, and send the log here?

**Comment by dandamusix95** [comment] 2021-02-18 23:27
The antivirus software is Webroot v9.0.29.62 and McAfee LiveSafe v14.0.

**Comment by dandamusix95** [comment] 2021-02-22 02:51
> Could you please enable the debug log, and send the log here?

Yes. OmniMIDI's debug log say this after opening Zenith:

OmniMIDI version 13.5.0.0
========= Debug information =========
Driver version: 13.5.0.0
Current MIDI app: None (N/A)
Active voices: 0
Average voices per frame: 0 V/f
Rendering time: 0.0%
Audio latency: Unavailable
App's working set size: No usage
App's handles count: 0 handles
KDMAPI status: Unavailable

**Comment by KaleidonKep99** [comment] 2021-02-22 14:22
> Yes. OmniMIDI's debug log say this after opening Zenith:

Sorry, I wasn't specific when I asked about the debug log!
The actual debug log can be enabled here:
![xnviewmp_w4hOZ5ugAs](https://user-images.githubusercontent.com/11065274/108720995-c7b79580-7521-11eb-828e-e78438093000.jpg)

**Comment by dandamusix95** [comment] 2021-02-22 21:26
> > Yes. OmniMIDI's debug log say this after opening Zenith:
> 
> Sorry, I wasn't specific when I asked about the debug log!
> The actual debug log can be enabled here:
> ![xnviewmp_w4hOZ5ugAs](https://user-images.githubusercontent.com/11065274/108720995-c7b79580-7521-11eb-828e-e78438093000.jpg)

Found it. 

=======================================
OmniMIDI 13.5.0 (KDMAPI 2.1.0, Revision 69)
4 threads available to the ASIO engine
Copyright(C) 2013 - KaleidonKep99

22-02-2021 16:20:16.662 - Stage <<StartDriver>> | Checking if app is allowed to use RTSS OSD...
22-02-2021 16:20:16.678 - Stage <<StartDriver>> | Initializing driver...
22-02-2021 16:20:16.678 - Stage <<ImportBASS>> | Importing BASS DLLs to memory...
22-02-2021 16:20:16.678 - Library <<bass.dll>> | No library has been found in memory. The driver will now load the DLL...
22-02-2021 16:20:16.678 - Library <<bass.dll>> | Checking through GetModuleHandle...
22-02-2021 16:20:16.779 - Library <<bass.dll>> | The library is now in memory.
22-02-2021 16:20:16.779 - Library <<basswasapi.dll>> | No library has been found in memory. The driver will now load the DLL...
22-02-2021 16:20:16.779 - Library <<basswasapi.dll>> | Checking through GetModuleHandle...
22-02-2021 16:20:17.117 - Library <<basswasapi.dll>> | The library is now in memory.
22-02-2021 16:20:17.117 - Library <<bassmidi.dll>> | No library has been found in memory. The driver will now load the DLL...
22-02-2021 16:20:17.117 - Library <<bassmidi.dll>> | Checking through GetModuleHandle...
22-02-2021 16:20:17.335 - Library <<bassmidi.dll>> | The library is now in memory.
22-02-2021 16:20:17.335 - Library <<bassenc.dll>> | No library has been found in memory. The driver will now load the DLL...
22-02-2021 16:20:17.335 - Library <<bassenc.dll>> | Checking through GetModuleHandle...
22-02-2021 16:20:17.468 - Library <<bassenc.dll>> | The library is now in memory.
22-02-2021 16:20:17.468 - Library <<bassasio.dll>> | No library has been found in memory. The driver will now load the DLL...
22-02-2021 16:20:17.468 - Library <<bassasio.dll>> | Checking through GetModuleHandle...
22-02-2021 16:20:17.744 - Library <<bassasio.dll>> | The library is now in memory.
22-02-2021 16:20:17.744 - Stage <<ImportBASS>> | DLLs loaded into memory. Importing functions...
22-02-2021 16:20:17.744 - Library <<bassflac.dll>> | No plugin has been found in memory. The driver will now load the DLL...
22-02-2021 16:20:18.106 - Library <<bassflac.dll>> | The plugin is now in memory.
22-02-2021 16:20:18.106 - Library <<basswv.dll>> | No plugin has been found in memory. The driver will now load the DLL...

**Comment by KaleidonKep99** [comment] 2021-02-23 14:46
I might have found what the issue is.
Apparently BASS does check if it's signed, and if the sign it's been signed with isn't valid, it'll complain about tampering.
I removed the self-sign in 13.5.2, and in my VM testing, the issue does not occur anymore.

Let me know if it's still happening.

**Comment by KaleidonKep99** [comment] 2021-02-23 21:53
Fixed in 13.6.

**Closed as completed by KaleidonKep99** 2021-02-23 21:53 UTC
Labels: Bug
