### ISSUE TITLE
Weird behaviour in all FL Studios on pitch change events

### ISSUE THREAD

**Issue by DixelU** [KaleidonKep99/OmniMIDI#126] opened 2018-11-25 05:52 UTC
I'm not sure if that's really OM's bug, since this thing happens only in FL.
Pitch goes to its minimum after any pitch change event, and stutters in the process of pitch's changing (video bellow)
[bandicam 2018-11-25 10-39-18-971.zip](https://github.com/KeppySoftware/OmniMIDI/files/2612856/bandicam.2018-11-25.10-39-18-971.zip)

**Comment by KaleidonKep99** [comment] 2018-11-25 06:31
The issue is not present in FL Studio 20.
https://www.youtube.com/watch?v=M7C7gHwqiE0

**Comment by DixelU** [comment] 2018-11-25 07:58
I've tested it in FL 12 and FL 20, both behave exactly the same

**Comment by KaleidonKep99** [comment] 2018-11-25 23:48
What version of OmniMIDI are you using?

**Comment by DixelU** [comment] 2018-11-26 16:48
6.0.57.20

Also found VBKP behaving almost the same on pitch changes which jumping from negative to positive value (pic bellow)
I'm not sure if there are any other affected applications...
[bandicam 2018-11-26 21-38-02-205.zip](https://github.com/KeppySoftware/OmniMIDI/files/2616515/bandicam.2018-11-26.21-38-02-205.zip)
![image](https://user-images.githubusercontent.com/26818917/49028981-721aa400-f1c5-11e8-88cf-008a97bd08af.png)

**Comment by KaleidonKep99** [comment] 2018-11-26 16:56
Reinstall OmniMIDI from scratch by using the configurator, then update to 6.0.57.22.

**Comment by KaleidonKep99** [comment] 2018-11-26 16:58
Oops I accidentally closed it.

**Comment by DixelU** [comment] 2018-11-26 17:11
I found what's that
That is the problem with parsing events with "enabled" running status on meta events (especially pitch bend control events)
As i've removed check mark from this, the issue in VBKP just stopped appearing.
![image](https://user-images.githubusercontent.com/26818917/49029964-d9395800-f1c7-11e8-9f06-fe8988b5ae2e.png)

**Comment by KaleidonKep99** [comment] 2018-11-26 17:12
That checkbox is meant to be enabled only with hardware MIDI devices, such as a Roland Sound Canvas.
OmniMIDI does not return the running status, since it's not mandatory for user-mode drivers.

I guess it's fixed then.

**Closed as completed by KaleidonKep99** 2018-11-26 17:12 UTC
Labels: Bug, Host application issue

**Comment by DixelU** [comment] 2018-11-26 17:15
Wait, there's still the same thing with FL
There is no check box with enabling/disabling running status.
ik, that's host app issue then, but what should i do now? .-.

**Comment by KaleidonKep99** [comment] 2018-11-26 17:19
As I said, reinstall the driver from scratch.
![image](https://user-images.githubusercontent.com/11065274/49030499-c1ea7280-f1a7-11e8-9a7f-9354e312dd67.png)

Then update to 6.0.57.22 without changing any setting.

**Comment by KaleidonKep99** [comment] 2018-11-26 17:31
Oh yeah, "Send master sync" is the same thing as "Enable running status".
Disable it!

I don't even know why you enable things without knowing what they do in the first place... 😂

**Comment by DixelU** [comment] 2018-11-26 17:43
Oof, thanks xd
That was enabled when i've opened FL11 for the first time, since that i usually reenable it
Also helps enabling this thing.
Prob some events getting lost while playback
![image](https://user-images.githubusercontent.com/26818917/49031774-bd848080-f1cc-11e8-8cdf-cfa624e0e288.png)

**Comment by KaleidonKep99** [comment] 2018-11-27 07:07
I added support for Running Status to OmniMIDI 6.0.57.23.
It should be available soon.
