### ISSUE TITLE
OmniMIDI not working on 32-bit Windows due to RunDLL Error

### ISSUE THREAD

**Issue by cedar515** [KaleidonKep99/OmniMIDI#192] opened 2021-06-05 18:35 UTC
**Problem**
OmniMIDI RunDLL Problem on 32-bit Windows making the synthesizer unusable for both Piano From Above and Synthesia.

**Steps to reproduce**
1. Register driver in application
or 2. Patch a midi app using WMW in OmniMIDI 
3. See error

**Expected behavior**
OmniMIDI running without RunDLL problem and working on Synthesia and PFA.

**Screenshots/Videos**
_Error when registering driver._
![attachment1](https://user-images.githubusercontent.com/85410306/120901265-4ddc8f80-c66c-11eb-9261-9dcbb7de0553.png)
_OmniMIDI not listed in PFA._
![attachment3](https://user-images.githubusercontent.com/85410306/120901289-7a90a700-c66c-11eb-924d-e425982bc936.png)
_OmniMIDI not listed in Synthesia._
![attachment2](https://user-images.githubusercontent.com/85410306/120901294-83817880-c66c-11eb-99c1-feb2427cacac.png)

**Environment**
 - Operating system: Windows 10 Pro x86 (32-Bit)
 - CPU: AMD Sempron 145 - 2.8GHz Single Core
 - RAM: 3 GB (2.9 GB total)
 - MIDI application: None
 - Version of the driver: 13.8.3.0

**Additional context**
A dll problem is causing OmniMIDI to not be listed in Synthesia and PFA for some reason. I tried patching both Synthesia and PFA using Windows Multimedia Wrapper, it crashes both midi apps on launch with error saying KDMAPI failed with note "_LoadLibraryW for OmniMIDI.dll failed. Can not load OmniMIDI to memory_"
I even tried uninstalling the laggy alternative I had which is **CoolSoft VirtualMIDISynth** but it did not fix the problem.

**Comment by KaleidonKep99** [comment] 2021-06-05 22:41
Windows x86 on an AMD64 CPU? Weird. 🐸 
I'll check what the issue is in a x86 VM.

**Comment by KaleidonKep99** [comment] 2021-06-05 23:16
Fixed in 13.8.6! Let me know if it works for you as well.

**Comment by cedar515** [comment] 2021-06-05 23:40
> Fixed in 13.8.6! Let me know if it works for you as well.

OmniMIDI showed up, **however there is a new problem.**

**_Apps crash when I try to press and enable OmniMIDI_**
![stop1](https://user-images.githubusercontent.com/85410306/120908166-3c11e100-c69a-11eb-8957-db21616cc5c0.png)
![stop2](https://user-images.githubusercontent.com/85410306/120908167-3e743b00-c69a-11eb-8d98-1e035366b98a.png)

**Comment by cedar515** [comment] 2021-06-05 23:42
noting that when I set the output to OmniMidi on both Synthesia and PFA's configurators, they refuse to start until the Midi out is set back to Microsoft GS Wavetable Synth

**Comment by KaleidonKep99** [comment] 2021-06-05 23:47
I think it's because basswasapi.dll is missing! My fault!
I'll fix it asap... (I'm messing everything up lately 😓)

**Comment by cedar515** [comment] 2021-06-06 00:11
> I think it's because basswasapi.dll is missing! My fault!
> I'll fix it asap... (I'm messing everything up lately 😓)


**it almost started to work on Synthesia but instead it just freezes and crashes**
![synthesia not working](https://user-images.githubusercontent.com/85410306/120908588-4c2bbf80-c69e-11eb-8852-92e23c980bf6.png)

but the synthesizer is **now working on PFA.**
![pfa working](https://user-images.githubusercontent.com/85410306/120908591-51890a00-c69e-11eb-8b33-86f33ce455fb.png)

Thanks for the help and fix Keppy, I'll guess I'll stick to PFA for now.
oh also, where can I get the KSP 7.0 soundfont?

**Comment by KaleidonKep99** [comment] 2021-06-06 00:22
> 
> 
> > I think it's because basswasapi.dll is missing! My fault!
> > I'll fix it asap... (I'm messing everything up lately 😓)
> 
> **it almost started to work on Synthesia but instead it just freezes and crashes**
> ![synthesia not working](https://user-images.githubusercontent.com/85410306/120908588-4c2bbf80-c69e-11eb-8852-92e23c980bf6.png)
> 
> but the synthesizer is **now working on PFA.**
> ![pfa working](https://user-images.githubusercontent.com/85410306/120908591-51890a00-c69e-11eb-8b33-86f33ce455fb.png)
> 
> Thanks for the help and fix Keppy, I'll guess I'll stick to PFA for now.
> oh also, where can I get the KSP 7.0 soundfont?

Sadly Synthesia has conflicts with OmniMIDI, because of its usage of the same BASS/BASSMIDI libraries.
KSP is not available anymore.

**Closed as completed by KaleidonKep99** 2021-06-06 00:22 UTC
Labels: Bug
