### ISSUE TITLE
Blacklist system is broken

### ISSUE THREAD

**Issue by longnguyen2004** [KaleidonKep99/OmniMIDI#46] opened 2016-12-21 02:36 UTC
Now every MIDI applications I use are blacklisted by KS (even though I haven't blacklisted anything).

**Comment by KaleidonKep99** [comment] 2016-12-21 06:13
Clean the user blacklist.

**Comment by longnguyen2004** [comment] 2016-12-21 09:55
I already tried cleaning it, doesn't work.

**Comment by KaleidonKep99** [comment] 2016-12-21 10:04
It's weird, because I can use it just fine...

**Comment by longnguyen2004** [comment] 2016-12-21 14:00
I'll try it on my other computer.

**Comment by longnguyen2004** [comment] 2016-12-21 14:55
So the bug is only there if I blacklisted something (in my case, a VoIP program).

**Comment by KaleidonKep99** [comment] 2016-12-21 16:55
Oh yea, now I see what the issue is.
It'll get fixed on version 4.0.5.6.

**Comment by KaleidonKep99** [comment] 2016-12-21 17:07
Here: https://github.com/KaleidonKep99/Keppy-s-Synthesizer/releases/tag/4.0.5.6

**Closed as completed by KaleidonKep99** 2016-12-21 17:07 UTC
Labels: Bug
