### ISSUE TITLE
Sysex messages are always ignored when "Ignore Sysex messages" are enabled

### ISSUE THREAD

**Issue by DevanWolf** [KaleidonKep99/OmniMIDI#43] opened 2016-12-02 23:52 UTC
There is a bug with the new feature in Keppy's Synthesizer where Sysex messages are always ignored no matter when Ignore Sysex messages are enabled and disabled.

**Comment by KaleidonKep99** [comment] 2016-12-03 02:59
They work just fine for me.
Remember that SysEx messages can ALSO be ignored by the application itself. (PFA doesn't recognize them, and VanBasco allow users to ignore them)

**Comment by KaleidonKep99** [comment] 2016-12-03 03:00
I accidentally closed it oops.

**Comment by KaleidonKep99** [comment] 2016-12-03 04:16
Also, let me know if the issue is still present in [version 4.0.5.1](https://github.com/KaleidonKep99/Keppy-s-Synthesizer/releases/tag/4.0.5.1).

**Comment by KaleidonKep99** [comment] 2016-12-09 21:23
It seems to work. Closed.

**Closed as completed by KaleidonKep99** 2016-12-09 21:23 UTC
Labels: Bug
